### PR TITLE
Add ability to parse URLs

### PR DESCRIPTION
**Pull request by pcman312**

### CODE REVIEW

**Comment by pcman312** [comment]
@caarlos0 please review?

**Comment by caarlos0** [comment]
can't you use string instead and convert to a url in your code?

**Comment by pcman312** [comment]
Yes that's how I've been doing it and it's annoying to have to do that for multiple URLs.

**Comment by caarlos0** [comment]
I understand, but, I prefer to keep the API as leaner as possible...

**Pull request closed without merging**
