### PR TITLE
support uint64 and []uint64

### PR DESCRIPTION
**Pull request by se3000**
We can't add custom parsers, since unint64 is a primitive and not a struct, this PR adds support for parsing uint64 and slices of uint64.

### CODE REVIEW

**Comment by caarlos0** [comment]
hey @se3000 , can you resolve the conflicts, please?

**Comment by Empact** [comment]
@caarlos0 resolved

**Comment by Empact** [comment]
@caarlos0 Went ahead and got us back up to 100% coverage as well.

**Comment by caarlos0** [comment]
> @caarlos0 Went ahead and got us back up to 100% coverage as well.

thankssss

**Pull request merged**
